name: Build and Test Backend Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Java Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          for dir in discovery-service config-service api-gateway user-service event-service booking-service; do
            if [ -f "$dir/pom.xml" ]; then
              mvn -f $dir/pom.xml clean install
            fi
          done
